/*
 *
 * Settings constants
 *
 */

export const DEFAULT_ACTION = 'app/Settings/DEFAULT_ACTION';
// constants for fetching user detail
export const FETCH_PROFILE_DETAIL = 'app/Settings/FETCH_PROFILE_DETAIL';
export const FETCH_PROFILE_DETAIL_SUCCESS = 'app/Settings/FETCH_PROFILE_DETAIL_SUCCESS';
export const FETCH_PROFILE_DETAIL_FAILED = 'app/Settings/FETCH_PROFILE_DETAIL_FAILED';

export const UPDATE_PROFILE_DETAIL = 'app/Settings/UPDATE_PROFILE_DETAIL';
export const UPDATE_PROFILE_DETAIL_SUCCESS = 'app/Settings/UPDATE_PROFILE_DETAIL_SUCCESS';
export const UPDATE_PROFILE_DETAIL_FAILED = 'app/Settings/UPDATE_PROFILE_DETAIL_FAILED';

export const GET_LANGUAGES = 'app/Settings/GET_LANGUAGES';
export const GET_LANGUAGES_SUCCESS = 'app/Settings/GET_LANGUAGES_SUCCESS';
export const GET_LANGUAGES_FAILED = 'app/Settings/GET_LANGUAGES_FAILED';

export const GET_SPECIALTIES_BY_PROFESSION = 'app/Settings/GET_SPECIALTIES_BY_PROFESSION';
export const GET_SPECIALTIES_BY_PROFESSION_SUCCESS = 'app/Settings/GET_SPECIALTIES_BY_PROFESSION_SUCCESS';
export const GET_SPECIALTIES_BY_PROFESSION_FAILED = 'app/Settings/GET_SPECIALTIES_BY_PROFESSION_FAILED';
